[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:suicide/nvim-conf.git"
    refreshPeriod = "24h"
[".config/awesome/freedesktop"]
    type = "git-repo"
    url = "git@github.com:lcpz/awesome-freedesktop.git"
    refreshPeriod = "168h"
[".config/awesome/lain"]
    type = "git-repo"
    url = "git@github.com:lcpz/lain.git"
    refreshPeriod = "168h"
[".bin/jenv"]
    type = "git-repo"
    url = "https://github.com/jenv/jenv.git"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
